spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/db_store
    url: jdbc:mysql://39.107.80.56:3306/computer_store
    username: firenut
    password: 123456


# 配置mybatis规则
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

